// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1_9RBuV2jrKTEbJcVVcLyzriygvrrqHo',
    appId: '1:574802963369:web:8796756e6fd5fc075e32b8',
    messagingSenderId: '574802963369',
    projectId: 'fir-login-58dbb',
    authDomain: 'fir-login-58dbb.firebaseapp.com',
    storageBucket: 'fir-login-58dbb.firebasestorage.app',
    measurementId: 'G-15F11ZE9EJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZW0vu3_k4mLb82iSlbJ0yPa8w1myu5b0',
    appId: '1:574802963369:android:a851360e580348645e32b8',
    messagingSenderId: '574802963369',
    projectId: 'fir-login-58dbb',
    storageBucket: 'fir-login-58dbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-MSKsuKjGt-kVq42r2L2ZCC5_54DCX5M',
    appId: '1:574802963369:ios:034c2a13b22d7e375e32b8',
    messagingSenderId: '574802963369',
    projectId: 'fir-login-58dbb',
    storageBucket: 'fir-login-58dbb.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-MSKsuKjGt-kVq42r2L2ZCC5_54DCX5M',
    appId: '1:574802963369:ios:034c2a13b22d7e375e32b8',
    messagingSenderId: '574802963369',
    projectId: 'fir-login-58dbb',
    storageBucket: 'fir-login-58dbb.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1_9RBuV2jrKTEbJcVVcLyzriygvrrqHo',
    appId: '1:574802963369:web:918db606d4afdb755e32b8',
    messagingSenderId: '574802963369',
    projectId: 'fir-login-58dbb',
    authDomain: 'fir-login-58dbb.firebaseapp.com',
    storageBucket: 'fir-login-58dbb.firebasestorage.app',
    measurementId: 'G-L2VKE9FFCM',
  );
}
